### ISSUE TITLE
[consensus] refactor code and implement new db interface

### ISSUE THREAD

**Issue by 0xmerman** [incognitochain/incognito-chain#476]
related #396 (design in draw.io and google presentation)
Implementation step:
- [x] Remove normal token #486 
- [x] Refactor current database code #486 
- [x] Complete rawdb package #486 
- [x] Add database interface: intermediate writer, database access warper for statedb, statedb (according to design spec) #518
- [x] add tire: #524
- [x] statedb package #549
- [x] add one (sample) state object into statedb package #549

**Comment by 0xmerman** [comment]
Update 20/11/2019:
Issue 1:
- Remove normal tx and re-write integration test done
- One issue remain in bridge rpc function (@minhduccm to fix)

**Comment by thaibao-incognito** [comment]
Split to many issues for easy pull request

**Comment by 0xmerman** [comment]
package trie is reuse mostly from ethereum source code, and require deep inspection in the future

**Comment by 0xmerman** [comment]
finished at 6/12/2019 as planned
