### ISSUE TITLE
[highway] Highway v1

### ISSUE THREAD

**Issue by 0xbunyip** [incognitochain/incognito-chain#605]
## Scope:
Multiple highways, each highway supports all shards
## Tasks:
- [x] Add tests for package peerv2 (13/12/2019) #609 
- [x] Add tests for synker (only logic related to highway) (17/12/2019) #630 
- [x] Finalize scope of highway v1 (16/12/2019)
- [x] Update spec for highway v1 (17/12/2019) [spec](https://docs.google.com/document/d/1dPT63o67ooiYPhBLjAuMZj3yUw8wW6klHx_nmMvVfwk/edit?pli=1#heading=h.m1ruskh5hb4h)

#### Pubsub ([PR](https://github.com/incognitochain/incognito-highway/pull/78))
- [x] Separate handler for each topic
- [x] Update handler for topics between node and highway
- [x] Handler for topics between highways

#### Request
- [x] Update peerstate msg to contain original highway
- [x] Delete old peerstate based on last seen time
- [x] Pick peer to request for supported shards ([PR](https://github.com/incognitochain/incognito-highway/pull/77))
- [x] Pick peer for non-supported shards
- [x] Add callstack to prevent infinite request loop

#### Highway network ([PR](https://github.com/incognitochain/incognito-highway/pull/73))
- [x] RPC get all highways online
- [x] Maintain highway connections (supported and non-supported shards)
- [x] Enlist new highway
- [x] Retry disconnected highway

#### Node's connections ([PR](https://github.com/incognitochain/incognito-chain/pull/644))
- [x] RPC get all highways online
- [x] Maintain connection
- [x] Retry disconnected highway (pick one highway from list)

#### Tests
- [x] Unit tests for route package ([PR](https://github.com/incognitochain/incognito-highway/pull/87))
- [x] Unit tests for chain package ([PR](https://github.com/incognitochain/incognito-highway/pull/88))

**Comment by 0xbunyip** [comment]
Timeline:
- [ ] Devnet: 27/12/2019
- [ ] Testnet: 02/01/2020
- [ ] Mainnet: 08/01/2020
