### ISSUE TITLE
Highway v2

### ISSUE THREAD

**Issue by 0xbunyip** [incognitochain/incognito-chain#738]
## Scope:
Optimize highway (cache and stream blocks)

## Timeline:
- [x] Devnet (24/02/2020)
- [x] Testnet (02/03/2020)
- [x] Mainnet (09/03/2020)

## Tasks:
- [x] Update spec for highway v2 (07/02/2020) [spec](https://docs.google.com/document/d/1dPT63o67ooiYPhBLjAuMZj3yUw8wW6klHx_nmMvVfwk/edit?pli=1#heading=h.m1ruskh5hb4h)
- [ ] Benchmark current sync time & bandwidth used

#### Streaming
<li> [x] Streaming data from node to highway (HW request Node) and from HW to node
<ul>
<li> [x] Block beacon </li>
<li> [x] Refactor requester/provider/netsync </li>
<li> [x] Block shard </li>
<li> [x] Block shard to beacon </li>
<li> [x] Block cross shard </li>
</ul>
</li>

#### Caching
- [x] Cache data in memory
~~- [ ] Persist data on disk (???)~~
- [x] Monitor cache hit rate

#### Tests
- [x] Update test for peerv2
